### ISSUE TITLE
打印成PDF后**加粗**的内容不被显示

### ISSUE THREAD

**Issue by ChrisCHEN502** [TriDiamond/Obsidian-Obsidianite#14]
非常好看的主题
应用该主题后，在把文档打印成PDF时加粗的内容显示不出来。
![image](https://user-images.githubusercontent.com/34997106/100966616-555d9780-3568-11eb-9ccc-aa93508b39c3.png)
如上，不被显示，但是可以复制

**Comment by TriDiamond** [comment]
Duplicate of #16

**Comment by TriDiamond** [comment]
感谢你的反馈，我会去看看这种问题的。
