### ISSUE TITLE
Pink underline on Header 2 does not render properly

### ISSUE THREAD

**Issue by ellekaie** [TriDiamond/Obsidian-Obsidianite#15]
Steps to Reproduce

1. Create note with this content:

# 400 Personal Development MOC

## Prompts
[[6 Questions to Ask Yourself If You're Feeling Lost]]
[[Fear-setting by Tim Ferriss]]

## Articles
[[21 Ways Self-Aware People Interact With The World Differently]]

## Quotes
[[A lion doesn't concern itself with the opinion of sheep]]
[[Better be the head of a chicken than the tail of a bull]]

2. Preview note 

Result:

![Issue 1](https://user-images.githubusercontent.com/31374592/101295516-08740c80-3859-11eb-919e-ef119cd362a8.png)

When I added another Header 2 under ## Quotes:
![Issue 2](https://user-images.githubusercontent.com/31374592/101295552-4bce7b00-3859-11eb-8f9f-e181e38c951f.PNG)

Adding Header 2 above ## Quotes:
![Issue 3](https://user-images.githubusercontent.com/31374592/101295581-76b8cf00-3859-11eb-85a7-b896704f3dc0.PNG)

Really love this theme, so I hope this can be fixed.

**Comment by ellekaie** [comment]
Found another way to reproduce the issue:

# 400 Personal Development MOC

[[Disrupting Thinking]]

## Prompts
[[6 Questions to Ask Yourself If You're Feeling Lost]]
[[Fear-setting by Tim Ferriss]]

## Articles
[[21 Ways Self-Aware People Interact With The World Differently]]

## Quotes
[[A lion doesn't concern itself with the opinion of sheep]]
[[Better be the head of a chicken than the tail of a bull]]

Result:
![Issue 4](https://user-images.githubusercontent.com/31374592/101295745-81279880-385a-11eb-884f-c0236340220f.PNG)

**Comment by ellekaie** [comment]
Encountered same issue, but this time it happens on edit mode (and not preview mode).

# 200 Literature

## Book

### Non-fiction
[[The Tools by Stutz & Michels]]
[[Pale Blue Dot by Carl Sagan]]


### Fiction

## Poem
[[Desiderata]]
[[Heaven is my father and Earth is my mother]]

## Essay
[[The Misbehavioral Sciences by Barzun]]

Result:
![Issue 6](https://user-images.githubusercontent.com/31374592/101295902-4d00a780-385b-11eb-85cf-b0106309459f.PNG)

**Comment by TriDiamond** [comment]
Thanks for reporting, I will look into this type of problems. @ellekaie

**Comment by ellekaie** [comment]
My new laptop just came and the bugs are not showing anymore. I'm back to this theme now!

**Comment by TriDiamond** [comment]
@ellekaie Fixed in [version 1.1.4](https://github.com/TriDiamond/Obsidian-Obsidianite/releases/tag/1.1.4)
