### ISSUE TITLE
Keystroke tags (<kbd>) are not rendered

### ISSUE THREAD

**Issue by VictorGrycuk** [TriDiamond/Obsidian-Obsidianite#18]
### Environment
- **Obsidian Version:** `v0.9.20`
- **Obsidianite Version:** `latest`
- **Custom CSS:** No

### Problem
I am trying to note down some shortcuts using the [markdown keystroke notation](https://meta.stackexchange.com/questions/70356/key-stroke-combination-markdown), but it does not seem to render correctly when using Obsidianite. However, it does work correctly when using the default Obsidian theme.

Would it be possible to add support for `<kbd>`?

_Obsidian default theme vs Obsidianite theme_
![image](https://user-images.githubusercontent.com/39467613/101658136-7a984d00-3a23-11eb-9890-2a50cab34578.png)

**Comment by TriDiamond** [comment]
Will work on this, thanks for reporting this. @VictorGrycuk

**Comment by TriDiamond** [comment]
This issue is only happening if we add bold to the <kbd>, this has to do with the bold text css styles. I will fix this in the next version.

**Comment by VictorGrycuk** [comment]
Thank you!

**Comment by TriDiamond** [comment]
@VictorGrycuk Fixed in [version 1.1.4](https://github.com/TriDiamond/Obsidian-Obsidianite/releases/tag/1.1.4)
