### ISSUE TITLE
Indent on first line of code block

### ISSUE THREAD

**Issue by Snuzzn** [TriDiamond/Obsidian-Obsidianite#20]
Obsidian 0.9.22, Obsidianite 1.1.3

In Preview Mode, there seems to be a small indent before the first line of code in a code block. Is there a way to remove this?
## Obsidianite
![image](https://user-images.githubusercontent.com/68191852/102681026-06735b80-4212-11eb-8152-890ccf6038af.png)

## No theme
![image](https://user-images.githubusercontent.com/68191852/102681115-f27c2980-4212-11eb-9226-87e317c042bd.png)

Really enjoying the theme btw :)

**Comment by ikelvinwoo** [comment]
I am experiencing the same issue, hope there is a fix coming soon.

**Comment by TriDiamond** [comment]
@Snuzzn @ikelvinwoo Thanks for reporting I will look into this for sure!

**Comment by TriDiamond** [comment]
Fixed in [version 1.1.4](https://github.com/TriDiamond/Obsidian-Obsidianite/releases/tag/1.1.4)
