### ISSUE TITLE
hope to get support with glowsansc

### ISSUE THREAD

**Issue by hong-tm** [TriDiamond/Obsidian-Obsidianite#3]
hope to get use glowsanssc font .tq

**Comment by TriDiamond** [comment]
Sure thing, just to make sure, is this what you are referring to?
https://github.com/welai/glow-sans

**Comment by hong-tm** [comment]
yup

**Comment by TriDiamond** [comment]
@hong-tm Support this font on version [1.0.4](https://github.com/TriDiamond/Obsidian-Obsidianite/releases/tag/1.0.4)
