### ISSUE TITLE
hope to get support for code block for visual basic?

### ISSUE THREAD

**Issue by hong-tm** [TriDiamond/Obsidian-Obsidianite#6]
![Snipaste_2020-11-09_22-38-12](https://user-images.githubusercontent.com/51999870/98555050-6b1acc80-22dc-11eb-8b17-b94ebad3be2c.png)
in obsidian
![Snipaste_2020-11-09_22-38-22](https://user-images.githubusercontent.com/51999870/98555058-6ce49000-22dc-11eb-89cc-b25e1fb655aa.png)
in typora

**Comment by TriDiamond** [comment]
This one has to do with plugin wise, just plain css can't support that for you.
