### ISSUE TITLE
Tags in Headings render very small

### ISSUE THREAD

**Issue by brimwats** [TriDiamond/Obsidian-Obsidianite#9]
Here's a screenshot: 

![image](https://user-images.githubusercontent.com/49103046/99723877-a7ca8e80-2a67-11eb-8692-562f7a0840df.png)

**Comment by TriDiamond** [comment]
@brimwats Got it, will fix that in the next release. Thanks for reporting.

**Comment by TriDiamond** [comment]
@brimwats Fixed in [version 1.1.4](https://github.com/TriDiamond/Obsidian-Obsidianite/releases/tag/1.1.4)
